name: netrafit
description: "Virtual Glass Frame Try-On App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.4
  camera: ^0.10.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^11.0.1
  webview_flutter: ^4.4.2
  webview_flutter_android:
  webview_flutter_wkwebview: ^3.0.5
  dio: ^5.3.3
  syncfusion_flutter_charts: ^31.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.jpg"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/